baseURL = "https://tripleat.github.io/TripleAtResume/"
languageCode = "ja-jp"
title = "YamadaTaishiResume"
theme = "hugo-resume"
publishDir = "docs"
canonifyurls = true


[params]
    firstName = "Taishi"
    lastName = "Yamada"
    address = "Oota-ku, Tokyo"
    contactNote = "Unity Engineer" #used in QR code only
    profileImage = "img/me.jpg"
    email = "omoitoomoi@gmail.com"
    description = "ソーシャルゲームの開発・運用を行う。主にフロントサイドを担当。Unityエンジニア"
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQr = true

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/OrotiYamatano"
    
[[params.handles]]
    name = "facebook"
    link = "https://www.facebook.com/omoitoomoi"


[[params.handles]]
    name = "Blog"
    link = "https://orotiyamatano.hatenablog.com/"

[[params.handles]]
    name = "Qiita"
    link = "https://qiita.com/OrotiYamatano"
    
[params.google.analytics]
    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]